kind: pipeline
type: docker
name: default

steps:
- name: validate
  image: hashicorp/packer:1.6.5
  environment:
    OCI_API_KEY_ENCODED:
      from_secret: OCI_API_KEY_ENCODED
  commands:
  - echo $OCI_API_KEY_ENCODED
  - packer validate hpc-image.json
