kind: pipeline
type: docker
name: default

steps:
- name: validate
  image: hashicorp/packer:1.6.5
  environment:
    TEST:
      from_secret: test
  commands:
  - echo $TEST
  - packer validate hpc-image.json
